# Generated by Django 4.0.2 on 2022-06-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='desc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
